# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Cupcake scheme by Chris Kempson (http://chriskempson.com)

[colors]
foreground = "#8b8198"
background = "#fbf1f2"

cursor_bg = "#8b8198"
cursor_border = "#8b8198"
cursor_fg = "#fbf1f2"

# selection_bg = "#fbf1f2"
# selection_fg = "#fbf1f2"

ansi = ["#fbf1f2", "#D57E85", "#A3B367", "#DCB16C", "#7297B9", "#BB99B4", "#69A9A7", "#8b8198"]
brights = ["#bfb9c6", "#EBB790", "#f2f1f4", "#d8d5dd", "#a59daf", "#72677E", "#BAA58C", "#585062"]

