# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# iA Dark scheme by iA Inc. (modified by aramisgithub)

[colors]
foreground = "#cccccc"
background = "#1a1a1a"

cursor_bg = "#cccccc"
cursor_border = "#cccccc"
cursor_fg = "#1a1a1a"

# selection_bg = "#1a1a1a"
# selection_fg = "#1a1a1a"

ansi = ["#1a1a1a", "#d88568", "#83a471", "#b99353", "#8eccdd", "#b98eb2", "#7c9cae", "#cccccc"]
brights = ["#767676", "#d86868", "#222222", "#1d414d", "#b8b8b8", "#e8e8e8", "#8b6c37", "#f8f8f8"]

