# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Grayscale Light scheme by Alexandre Gavioli (https://github.com/Alexx2/)

[colors]
foreground = "#464646"
background = "#f7f7f7"

cursor_bg = "#464646"
cursor_border = "#464646"
cursor_fg = "#f7f7f7"

# selection_bg = "#f7f7f7"
# selection_fg = "#f7f7f7"

ansi = ["#f7f7f7", "#7c7c7c", "#8e8e8e", "#a0a0a0", "#686868", "#747474", "#868686", "#464646"]
brights = ["#ababab", "#999999", "#e3e3e3", "#b9b9b9", "#525252", "#252525", "#5e5e5e", "#101010"]

