# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Atelier Seaside Light scheme by Bram de Haan (http://atelierbramdehaan.nl)

[colors]
foreground = "#5e6e5e"
background = "#f4fbf4"

cursor_bg = "#5e6e5e"
cursor_border = "#5e6e5e"
cursor_fg = "#f4fbf4"

# selection_bg = "#f4fbf4"
# selection_fg = "#f4fbf4"

ansi = ["#f4fbf4", "#e6193c", "#29a329", "#98981b", "#3d62f5", "#ad2bee", "#1999b3", "#5e6e5e"]
brights = ["#809980", "#87711d", "#cfe8cf", "#8ca68c", "#687d68", "#242924", "#e619c3", "#131513"]

