# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Materia scheme by Defman21

[colors]
foreground = "#CDD3DE"
background = "#263238"

cursor_bg = "#CDD3DE"
cursor_border = "#CDD3DE"
cursor_fg = "#263238"

# selection_bg = "#263238"
# selection_fg = "#263238"

ansi = ["#263238", "#EC5F67", "#8BD649", "#FFCC00", "#89DDFF", "#82AAFF", "#80CBC4", "#CDD3DE"]
brights = ["#707880", "#EA9560", "#2C393F", "#37474F", "#C9CCD3", "#D5DBE5", "#EC5F67", "#FFFFFF"]

