# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Solar Flare Light scheme by Chuck Harmston (https://chuck.harmston.ch)

[colors]
foreground = "#586875"
background = "#F5F7FA"

cursor_bg = "#586875"
cursor_border = "#586875"
cursor_fg = "#F5F7FA"

# selection_bg = "#F5F7FA"
# selection_fg = "#F5F7FA"

ansi = ["#F5F7FA", "#EF5253", "#7CC844", "#E4B51C", "#33B5E1", "#A363D5", "#52CBB0", "#586875"]
brights = ["#85939E", "#E66B2B", "#E8E9ED", "#A6AFB8", "#667581", "#222E38", "#D73C9A", "#18262F"]

