# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Material scheme by Nate Peterson

[colors]
foreground = "#EEFFFF"
background = "#263238"

cursor_bg = "#EEFFFF"
cursor_border = "#EEFFFF"
cursor_fg = "#263238"

# selection_bg = "#263238"
# selection_fg = "#263238"

ansi = ["#263238", "#F07178", "#C3E88D", "#FFCB6B", "#82AAFF", "#C792EA", "#89DDFF", "#EEFFFF"]
brights = ["#546E7A", "#F78C6C", "#2E3C43", "#314549", "#B2CCD6", "#EEFFFF", "#FF5370", "#FFFFFF"]

