# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Silk Light scheme by Gabriel Fontes (https://github.com/Misterio77)

[colors]
foreground = "#385156"
background = "#E9F1EF"

cursor_bg = "#385156"
cursor_border = "#385156"
cursor_fg = "#E9F1EF"

# selection_bg = "#E9F1EF"
# selection_fg = "#E9F1EF"

ansi = ["#E9F1EF", "#CF432E", "#6CA38C", "#CFAD25", "#39AAC9", "#6E6582", "#329CA2", "#385156"]
brights = ["#5C787B", "#D27F46", "#CCD4D3", "#90B7B6", "#4B5B5F", "#0e3c46", "#865369", "#D2FAFF"]

