# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Gigavolt scheme by Aidan Swope (http://github.com/Whillikers)

[colors]
foreground = "#e9e7e1"
background = "#202126"

cursor_bg = "#e9e7e1"
cursor_border = "#e9e7e1"
cursor_fg = "#202126"

# selection_bg = "#202126"
# selection_fg = "#202126"

ansi = ["#202126", "#ff661a", "#f2e6a9", "#ffdc2d", "#40bfff", "#ae94f9", "#fb6acb", "#e9e7e1"]
brights = ["#a1d2e6", "#19f988", "#2d303d", "#5a576e", "#cad3ff", "#eff0f9", "#6187ff", "#f2fbff"]

