# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Tomorrow Night scheme by Chris Kempson (http://chriskempson.com)

[colors]
foreground = "#cccccc"
background = "#2d2d2d"

cursor_bg = "#cccccc"
cursor_border = "#cccccc"
cursor_fg = "#2d2d2d"

# selection_bg = "#2d2d2d"
# selection_fg = "#2d2d2d"

ansi = ["#2d2d2d", "#f2777a", "#99cc99", "#ffcc66", "#6699cc", "#cc99cc", "#66cccc", "#cccccc"]
brights = ["#999999", "#f99157", "#393939", "#515151", "#b4b7b4", "#e0e0e0", "#a3685a", "#ffffff"]

