# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Atelier Lakeside Light scheme by Bram de Haan (http://atelierbramdehaan.nl)

[colors]
foreground = "#516d7b"
background = "#ebf8ff"

cursor_bg = "#516d7b"
cursor_border = "#516d7b"
cursor_fg = "#ebf8ff"

# selection_bg = "#ebf8ff"
# selection_fg = "#ebf8ff"

ansi = ["#ebf8ff", "#d22d72", "#568c3b", "#8a8a0f", "#257fad", "#6b6bb8", "#2d8f6f", "#516d7b"]
brights = ["#7195a8", "#935c25", "#c1e4f6", "#7ea2b4", "#5a7b8c", "#1f292e", "#b72dd2", "#161b1d"]

