# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Ocean scheme by Chris Kempson (http://chriskempson.com)

[colors]
foreground = "#c0c5ce"
background = "#2b303b"

cursor_bg = "#c0c5ce"
cursor_border = "#c0c5ce"
cursor_fg = "#2b303b"

# selection_bg = "#2b303b"
# selection_fg = "#2b303b"

ansi = ["#2b303b", "#bf616a", "#a3be8c", "#ebcb8b", "#8fa1b3", "#b48ead", "#96b5b4", "#c0c5ce"]
brights = ["#65737e", "#d08770", "#343d46", "#4f5b66", "#a7adba", "#dfe1e8", "#ab7967", "#eff1f5"]

