# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Tango scheme by @Schnouki, based on the Tango Desktop Project

[colors]
foreground = "#d3d7cf"
background = "#2e3436"

cursor_bg = "#d3d7cf"
cursor_border = "#d3d7cf"
cursor_fg = "#2e3436"

# selection_bg = "#2e3436"
# selection_fg = "#2e3436"

ansi = ["#2e3436", "#cc0000", "#4e9a06", "#c4a000", "#3465a4", "#75507b", "#06989a", "#d3d7cf"]
brights = ["#555753", "#ef2929", "#8ae234", "#fce94f", "#729fcf", "#ad7fa8", "#34e2e2", "#eeeeec"]

