# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Atelier Plateau Light scheme by Bram de Haan (http://atelierbramdehaan.nl)

[colors]
foreground = "#585050"
background = "#f4ecec"

cursor_bg = "#585050"
cursor_border = "#585050"
cursor_fg = "#f4ecec"

# selection_bg = "#f4ecec"
# selection_fg = "#f4ecec"

ansi = ["#f4ecec", "#ca4949", "#4b8b8b", "#a06e3b", "#7272ca", "#8464c4", "#5485b6", "#585050"]
brights = ["#7e7777", "#b45a3c", "#e7dfdf", "#8a8585", "#655d5d", "#292424", "#bd5187", "#1b1818"]

