# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Github scheme by Defman21

[colors]
foreground = "#333333"
background = "#ffffff"

cursor_bg = "#333333"
cursor_border = "#333333"
cursor_fg = "#ffffff"

# selection_bg = "#ffffff"
# selection_fg = "#ffffff"

ansi = ["#ffffff", "#ed6a43", "#183691", "#795da3", "#795da3", "#a71d5d", "#183691", "#333333"]
brights = ["#969896", "#0086b3", "#f5f5f5", "#c8c8fa", "#e8e8e8", "#ffffff", "#333333", "#ffffff"]

