# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# 3024 scheme by Jan T. Sott (http://github.com/idleberg)

[colors]
foreground = "#a5a2a2"
background = "#090300"

cursor_bg = "#a5a2a2"
cursor_border = "#a5a2a2"
cursor_fg = "#090300"

# selection_bg = "#090300"
# selection_fg = "#090300"

ansi = ["#090300", "#db2d20", "#01a252", "#fded02", "#01a0e4", "#a16a94", "#b5e4f4", "#a5a2a2"]
brights = ["#5c5855", "#e8bbd0", "#3a3432", "#4a4543", "#807d7c", "#d6d5d4", "#cdab53", "#f7f7f7"]

