# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Windows High Contrast Light scheme by Fergus Collins (https://github.com/C-Fergus)

[colors]
foreground = "#545454"
background = "#fcfcfc"

cursor_bg = "#545454"
cursor_border = "#545454"
cursor_fg = "#fcfcfc"

# selection_bg = "#fcfcfc"
# selection_fg = "#fcfcfc"

ansi = ["#fcfcfc", "#800000", "#008000", "#808000", "#000080", "#800080", "#008080", "#545454"]
brights = ["#c0c0c0", "#fcfc54", "#e8e8e8", "#d4d4d4", "#7e7e7e", "#2a2a2a", "#54fc54", "#000000"]

