# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Atelier Estuary Light scheme by Bram de Haan (http://atelierbramdehaan.nl)

[colors]
foreground = "#5f5e4e"
background = "#f4f3ec"

cursor_bg = "#5f5e4e"
cursor_border = "#5f5e4e"
cursor_fg = "#f4f3ec"

# selection_bg = "#f4f3ec"
# selection_fg = "#f4f3ec"

ansi = ["#f4f3ec", "#ba6236", "#7d9726", "#a5980d", "#36a166", "#5f9182", "#5b9d48", "#5f5e4e"]
brights = ["#878573", "#ae7313", "#e7e6df", "#929181", "#6c6b5a", "#302f27", "#9d6c7c", "#22221b"]

