# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Classic Dark scheme by Jason Heeris (http://heeris.id.au)

[colors]
foreground = "#D0D0D0"
background = "#151515"

cursor_bg = "#D0D0D0"
cursor_border = "#D0D0D0"
cursor_fg = "#151515"

# selection_bg = "#151515"
# selection_fg = "#151515"

ansi = ["#151515", "#AC4142", "#90A959", "#F4BF75", "#6A9FB5", "#AA759F", "#75B5AA", "#D0D0D0"]
brights = ["#505050", "#D28445", "#202020", "#303030", "#B0B0B0", "#E0E0E0", "#8F5536", "#F5F5F5"]

