# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Solarized Dark scheme by Ethan Schoonover (modified by aramisgithub)

[colors]
foreground = "#93a1a1"
background = "#002b36"

cursor_bg = "#93a1a1"
cursor_border = "#93a1a1"
cursor_fg = "#002b36"

# selection_bg = "#002b36"
# selection_fg = "#002b36"

ansi = ["#002b36", "#dc322f", "#859900", "#b58900", "#268bd2", "#6c71c4", "#2aa198", "#93a1a1"]
brights = ["#657b83", "#cb4b16", "#073642", "#586e75", "#839496", "#eee8d5", "#d33682", "#fdf6e3"]

