# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# London Tube scheme by Jan T. Sott

[colors]
foreground = "#d9d8d8"
background = "#231f20"

cursor_bg = "#d9d8d8"
cursor_border = "#d9d8d8"
cursor_fg = "#231f20"

# selection_bg = "#231f20"
# selection_fg = "#231f20"

ansi = ["#231f20", "#ee2e24", "#00853e", "#ffd204", "#009ddc", "#98005d", "#85cebc", "#d9d8d8"]
brights = ["#737171", "#f386a1", "#1c3f95", "#5a5758", "#959ca1", "#e7e7e8", "#b06110", "#ffffff"]

