# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Cupertino scheme by Defman21

[colors]
foreground = "#404040"
background = "#ffffff"

cursor_bg = "#404040"
cursor_border = "#404040"
cursor_fg = "#ffffff"

# selection_bg = "#ffffff"
# selection_fg = "#ffffff"

ansi = ["#ffffff", "#c41a15", "#007400", "#826b28", "#0000ff", "#a90d91", "#318495", "#404040"]
brights = ["#808080", "#eb8500", "#c0c0c0", "#c0c0c0", "#808080", "#404040", "#826b28", "#5e5e5e"]

