# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# iA Light scheme by iA Inc. (modified by aramisgithub)

[colors]
foreground = "#181818"
background = "#f6f6f6"

cursor_bg = "#181818"
cursor_border = "#181818"
cursor_fg = "#f6f6f6"

# selection_bg = "#f6f6f6"
# selection_fg = "#f6f6f6"

ansi = ["#f6f6f6", "#9c5a02", "#38781c", "#c48218", "#48bac2", "#a94598", "#2d6bb1", "#181818"]
brights = ["#898989", "#c43e18", "#dedede", "#bde5f2", "#767676", "#e8e8e8", "#8b6c37", "#f8f8f8"]

