# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Flat scheme by Chris Kempson (http://chriskempson.com)

[colors]
foreground = "#e0e0e0"
background = "#2C3E50"

cursor_bg = "#e0e0e0"
cursor_border = "#e0e0e0"
cursor_fg = "#2C3E50"

# selection_bg = "#2C3E50"
# selection_fg = "#2C3E50"

ansi = ["#2C3E50", "#E74C3C", "#2ECC71", "#F1C40F", "#3498DB", "#9B59B6", "#1ABC9C", "#e0e0e0"]
brights = ["#95A5A6", "#E67E22", "#34495E", "#7F8C8D", "#BDC3C7", "#f5f5f5", "#be643c", "#ECF0F1"]

