# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Google Dark scheme by Seth Wright (http://sethawright.com)

[colors]
foreground = "#c5c8c6"
background = "#1d1f21"

cursor_bg = "#c5c8c6"
cursor_border = "#c5c8c6"
cursor_fg = "#1d1f21"

# selection_bg = "#1d1f21"
# selection_fg = "#1d1f21"

ansi = ["#1d1f21", "#CC342B", "#198844", "#FBA922", "#3971ED", "#A36AC7", "#3971ED", "#c5c8c6"]
brights = ["#969896", "#F96A38", "#282a2e", "#373b41", "#b4b7b4", "#e0e0e0", "#3971ED", "#ffffff"]

