# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Atelier Dune scheme by Bram de Haan (http://atelierbramdehaan.nl)

[colors]
foreground = "#a6a28c"
background = "#20201d"

cursor_bg = "#a6a28c"
cursor_border = "#a6a28c"
cursor_fg = "#20201d"

# selection_bg = "#20201d"
# selection_fg = "#20201d"

ansi = ["#20201d", "#d73737", "#60ac39", "#ae9513", "#6684e1", "#b854d4", "#1fad83", "#a6a28c"]
brights = ["#7d7a68", "#b65611", "#292824", "#6e6b5e", "#999580", "#e8e4cf", "#d43552", "#fefbec"]

