# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Gruvbox dark, soft scheme by Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)

[colors]
foreground = "#d5c4a1"
background = "#32302f"

cursor_bg = "#d5c4a1"
cursor_border = "#d5c4a1"
cursor_fg = "#32302f"

# selection_bg = "#32302f"
# selection_fg = "#32302f"

ansi = ["#32302f", "#fb4934", "#b8bb26", "#fabd2f", "#83a598", "#d3869b", "#8ec07c", "#d5c4a1"]
brights = ["#665c54", "#fe8019", "#3c3836", "#504945", "#bdae93", "#ebdbb2", "#d65d0e", "#fbf1c7"]

