# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Synth Midnight Terminal Dark scheme by Michaël Ball (http://github.com/michael-ball/)

[colors]
foreground = "#c1c3c4"
background = "#050608"

cursor_bg = "#c1c3c4"
cursor_border = "#c1c3c4"
cursor_fg = "#050608"

# selection_bg = "#050608"
# selection_fg = "#050608"

ansi = ["#050608", "#b53b50", "#06ea61", "#c9d364", "#03aeff", "#ea5ce2", "#42fff9", "#c1c3c4"]
brights = ["#474849", "#ea770d", "#1a1b1c", "#28292a", "#a3a5a6", "#cfd1d2", "#cd6320", "#dddfe0"]

