# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Eva scheme by kjakapat (https://github.com/kjakapat)

[colors]
foreground = "#9fa2a6"
background = "#2a3b4d"

cursor_bg = "#9fa2a6"
cursor_border = "#9fa2a6"
cursor_fg = "#2a3b4d"

# selection_bg = "#2a3b4d"
# selection_fg = "#2a3b4d"

ansi = ["#2a3b4d", "#c4676c", "#66ff66", "#ffff66", "#15f4ee", "#9c6cd3", "#4b8f77", "#9fa2a6"]
brights = ["#55799c", "#ff9966", "#3d566f", "#4b6988", "#7e90a3", "#d6d7d9", "#bb64a9", "#ffffff"]

