# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# pinky scheme by Benjamin (https://github.com/b3nj5m1n)

[colors]
foreground = "#f5f5f5"
background = "#171517"

cursor_bg = "#f5f5f5"
cursor_border = "#f5f5f5"
cursor_fg = "#171517"

# selection_bg = "#171517"
# selection_fg = "#171517"

ansi = ["#171517", "#ffa600", "#ff0066", "#20df6c", "#00ffff", "#007fff", "#6600ff", "#f5f5f5"]
brights = ["#383338", "#00ff66", "#1b181b", "#1d1b1d", "#e7dbdb", "#ffffff", "#df206c", "#f7f3f7"]

