# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Chalk scheme by Chris Kempson (http://chriskempson.com)

[colors]
foreground = "#d0d0d0"
background = "#151515"

cursor_bg = "#d0d0d0"
cursor_border = "#d0d0d0"
cursor_fg = "#151515"

# selection_bg = "#151515"
# selection_fg = "#151515"

ansi = ["#151515", "#fb9fb1", "#acc267", "#ddb26f", "#6fc2ef", "#e1a3ee", "#12cfc0", "#d0d0d0"]
brights = ["#505050", "#eda987", "#202020", "#303030", "#b0b0b0", "#e0e0e0", "#deaf8f", "#f5f5f5"]

