# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# tender scheme by Jacobo Tabernero (https://github/com/jacoborus/tender.vim)

[colors]
foreground = "#eeeeee"
background = "#282828"

cursor_bg = "#eeeeee"
cursor_border = "#eeeeee"
cursor_fg = "#282828"

# selection_bg = "#282828"
# selection_fg = "#282828"

ansi = ["#282828", "#f43753", "#c9d05c", "#ffc24b", "#b3deef", "#d3b987", "#73cef4", "#eeeeee"]
brights = ["#4c4c4c", "#dc9656", "#383838", "#484848", "#b8b8b8", "#e8e8e8", "#a16946", "#feffff"]

