# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Material Vivid scheme by joshyrobot

[colors]
foreground = "#80868b"
background = "#202124"

cursor_bg = "#80868b"
cursor_border = "#80868b"
cursor_fg = "#202124"

# selection_bg = "#202124"
# selection_fg = "#202124"

ansi = ["#202124", "#f44336", "#00e676", "#ffeb3b", "#2196f3", "#673ab7", "#00bcd4", "#80868b"]
brights = ["#44464d", "#ff9800", "#27292c", "#323639", "#676c71", "#9e9e9e", "#8d6e63", "#ffffff"]

