# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Pasque scheme by Gabriel Fontes (https://github.com/Misterio77)

[colors]
foreground = "#DEDCDF"
background = "#271C3A"

cursor_bg = "#DEDCDF"
cursor_border = "#DEDCDF"
cursor_fg = "#271C3A"

# selection_bg = "#271C3A"
# selection_fg = "#271C3A"

ansi = ["#271C3A", "#A92258", "#C6914B", "#804ead", "#8E7DC6", "#953B9D", "#7263AA", "#DEDCDF"]
brights = ["#5D5766", "#918889", "#100323", "#3E2D5C", "#BEBCBF", "#EDEAEF", "#59325C", "#BBAADD"]

