# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Porple scheme by Niek den Breeje (https://github.com/AuditeMarlow)

[colors]
foreground = "#d8d8d8"
background = "#292c36"

cursor_bg = "#d8d8d8"
cursor_border = "#d8d8d8"
cursor_fg = "#292c36"

# selection_bg = "#292c36"
# selection_fg = "#292c36"

ansi = ["#292c36", "#f84547", "#95c76f", "#efa16b", "#8485ce", "#b74989", "#64878f", "#d8d8d8"]
brights = ["#65568a", "#d28e5d", "#333344", "#474160", "#b8b8b8", "#e8e8e8", "#986841", "#f8f8f8"]

