# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# OneDark scheme by Lalit Magant (http://github.com/tilal6991)

[colors]
foreground = "#abb2bf"
background = "#282c34"

cursor_bg = "#abb2bf"
cursor_border = "#abb2bf"
cursor_fg = "#282c34"

# selection_bg = "#282c34"
# selection_fg = "#282c34"

ansi = ["#282c34", "#e06c75", "#98c379", "#e5c07b", "#61afef", "#c678dd", "#56b6c2", "#abb2bf"]
brights = ["#545862", "#d19a66", "#353b45", "#3e4451", "#565c64", "#b6bdca", "#be5046", "#c8ccd4"]

