# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Framer scheme by Framer (Maintained by Jesse Hoyos)

[colors]
foreground = "#D0D0D0"
background = "#181818"

cursor_bg = "#D0D0D0"
cursor_border = "#D0D0D0"
cursor_fg = "#181818"

# selection_bg = "#181818"
# selection_fg = "#181818"

ansi = ["#181818", "#FD886B", "#32CCDC", "#FECB6E", "#20BCFC", "#BA8CFC", "#ACDDFD", "#D0D0D0"]
brights = ["#747474", "#FC4769", "#151515", "#464646", "#B9B9B9", "#E8E8E8", "#B15F4A", "#EEEEEE"]

