# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Google Light scheme by Seth Wright (http://sethawright.com)

[colors]
foreground = "#373b41"
background = "#ffffff"

cursor_bg = "#373b41"
cursor_border = "#373b41"
cursor_fg = "#ffffff"

# selection_bg = "#ffffff"
# selection_fg = "#ffffff"

ansi = ["#ffffff", "#CC342B", "#198844", "#FBA922", "#3971ED", "#A36AC7", "#3971ED", "#373b41"]
brights = ["#b4b7b4", "#F96A38", "#e0e0e0", "#c5c8c6", "#969896", "#282a2e", "#3971ED", "#1d1f21"]

