# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Classic Light scheme by Jason Heeris (http://heeris.id.au)

[colors]
foreground = "#303030"
background = "#F5F5F5"

cursor_bg = "#303030"
cursor_border = "#303030"
cursor_fg = "#F5F5F5"

# selection_bg = "#F5F5F5"
# selection_fg = "#F5F5F5"

ansi = ["#F5F5F5", "#AC4142", "#90A959", "#F4BF75", "#6A9FB5", "#AA759F", "#75B5AA", "#303030"]
brights = ["#B0B0B0", "#D28445", "#E0E0E0", "#D0D0D0", "#505050", "#202020", "#8F5536", "#151515"]

