# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Grayscale Dark scheme by Alexandre Gavioli (https://github.com/Alexx2/)

[colors]
foreground = "#b9b9b9"
background = "#101010"

cursor_bg = "#b9b9b9"
cursor_border = "#b9b9b9"
cursor_fg = "#101010"

# selection_bg = "#101010"
# selection_fg = "#101010"

ansi = ["#101010", "#7c7c7c", "#8e8e8e", "#a0a0a0", "#686868", "#747474", "#868686", "#b9b9b9"]
brights = ["#525252", "#999999", "#252525", "#464646", "#ababab", "#e3e3e3", "#5e5e5e", "#f7f7f7"]

