# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Macintosh scheme by Rebecca Bettencourt (http://www.kreativekorp.com)

[colors]
foreground = "#c0c0c0"
background = "#000000"

cursor_bg = "#c0c0c0"
cursor_border = "#c0c0c0"
cursor_fg = "#000000"

# selection_bg = "#000000"
# selection_fg = "#000000"

ansi = ["#000000", "#dd0907", "#1fb714", "#fbf305", "#0000d3", "#4700a5", "#02abea", "#c0c0c0"]
brights = ["#808080", "#ff6403", "#404040", "#404040", "#808080", "#c0c0c0", "#90713a", "#ffffff"]

