# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Green Screen scheme by Chris Kempson (http://chriskempson.com)

[colors]
foreground = "#00bb00"
background = "#001100"

cursor_bg = "#00bb00"
cursor_border = "#00bb00"
cursor_fg = "#001100"

# selection_bg = "#001100"
# selection_fg = "#001100"

ansi = ["#001100", "#007700", "#00bb00", "#007700", "#009900", "#00bb00", "#005500", "#00bb00"]
brights = ["#007700", "#009900", "#003300", "#005500", "#009900", "#00dd00", "#005500", "#00ff00"]

