# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Icy Dark scheme by icyphox (https://icyphox.ga)

[colors]
foreground = "#095b67"
background = "#021012"

cursor_bg = "#095b67"
cursor_border = "#095b67"
cursor_fg = "#021012"

# selection_bg = "#021012"
# selection_fg = "#021012"

ansi = ["#021012", "#16c1d9", "#4dd0e1", "#80deea", "#00bcd4", "#00acc1", "#26c6da", "#095b67"]
brights = ["#052e34", "#b3ebf2", "#031619", "#041f23", "#064048", "#0c7c8c", "#0097a7", "#109cb0"]

