# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Black Metal (Immortal) scheme by metalelf0 (https://github.com/metalelf0)

[colors]
foreground = "#c1c1c1"
background = "#000000"

cursor_bg = "#c1c1c1"
cursor_border = "#c1c1c1"
cursor_fg = "#000000"

# selection_bg = "#000000"
# selection_fg = "#000000"

ansi = ["#000000", "#5f8787", "#7799bb", "#556677", "#888888", "#999999", "#aaaaaa", "#c1c1c1"]
brights = ["#333333", "#aaaaaa", "#121212", "#222222", "#999999", "#999999", "#444444", "#c1c1c1"]

