# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# dirtysea scheme by Kahlil (Kal) Hodgson

[colors]
foreground = "#000000"
background = "#e0e0e0"

cursor_bg = "#000000"
cursor_border = "#000000"
cursor_fg = "#e0e0e0"

# selection_bg = "#e0e0e0"
# selection_fg = "#e0e0e0"

ansi = ["#e0e0e0", "#840000", "#730073", "#755B00", "#007300", "#000090", "#755B00", "#000000"]
brights = ["#707070", "#006565", "#d0dad0", "#d0d0d0", "#202020", "#f8f8f8", "#755B00", "#c4d9c4"]

