# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Windows 95 Light scheme by Fergus Collins (https://github.com/C-Fergus)

[colors]
foreground = "#545454"
background = "#fcfcfc"

cursor_bg = "#545454"
cursor_border = "#545454"
cursor_fg = "#fcfcfc"

# selection_bg = "#fcfcfc"
# selection_fg = "#fcfcfc"

ansi = ["#fcfcfc", "#a80000", "#00a800", "#a85400", "#0000a8", "#a800a8", "#00a8a8", "#545454"]
brights = ["#a8a8a8", "#fcfc54", "#e0e0e0", "#c4c4c4", "#7e7e7e", "#2a2a2a", "#54fc54", "#000000"]

