# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# summercamp scheme by zoe firi (zoefiri.github.io)

[colors]
foreground = "#736e55"
background = "#1c1810"

cursor_bg = "#736e55"
cursor_border = "#736e55"
cursor_fg = "#1c1810"

# selection_bg = "#1c1810"
# selection_fg = "#1c1810"

ansi = ["#1c1810", "#e35142", "#5ceb5a", "#f2ff27", "#489bf0", "#FF8080", "#5aebbc", "#736e55"]
brights = ["#504b38", "#fba11b", "#2a261c", "#3a3527", "#5f5b45", "#bab696", "#F69BE7", "#f8f5de"]

