# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Tomorrow Night scheme by Chris Kempson (http://chriskempson.com)

[colors]
foreground = "#c5c8c6"
background = "#1d1f21"

cursor_bg = "#c5c8c6"
cursor_border = "#c5c8c6"
cursor_fg = "#1d1f21"

# selection_bg = "#1d1f21"
# selection_fg = "#1d1f21"

ansi = ["#1d1f21", "#cc6666", "#b5bd68", "#f0c674", "#81a2be", "#b294bb", "#8abeb7", "#c5c8c6"]
brights = ["#969896", "#de935f", "#282a2e", "#373b41", "#b4b7b4", "#e0e0e0", "#a3685a", "#ffffff"]

