# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Darcula scheme by jetbrains

[colors]
foreground = "#a9b7c6"
background = "#2b2b2b"

cursor_bg = "#a9b7c6"
cursor_border = "#a9b7c6"
cursor_fg = "#2b2b2b"

# selection_bg = "#2b2b2b"
# selection_fg = "#2b2b2b"

ansi = ["#2b2b2b", "#4eade5", "#6a8759", "#bbb529", "#9876aa", "#cc7832", "#629755", "#a9b7c6"]
brights = ["#606366", "#689757", "#323232", "#323232", "#a4a3a3", "#ffc66d", "#808080", "#ffffff"]

