# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Windows NT Light scheme by Fergus Collins (https://github.com/C-Fergus)

[colors]
foreground = "#808080"
background = "#ffffff"

cursor_bg = "#808080"
cursor_border = "#808080"
cursor_fg = "#ffffff"

# selection_bg = "#ffffff"
# selection_fg = "#ffffff"

ansi = ["#ffffff", "#800000", "#008000", "#808000", "#000080", "#800080", "#008080", "#808080"]
brights = ["#c0c0c0", "#ffff00", "#eaeaea", "#d5d5d5", "#a0a0a0", "#404040", "#00ff00", "#000000"]

