# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# Horizon Light scheme by Michaël Ball (http://github.com/michael-ball/)

[colors]
foreground = "#403C3D"
background = "#FDF0ED"

cursor_bg = "#403C3D"
cursor_border = "#403C3D"
cursor_fg = "#FDF0ED"

# selection_bg = "#FDF0ED"
# selection_fg = "#FDF0ED"

ansi = ["#FDF0ED", "#E95678", "#29D398", "#FADAD1", "#26BBD9", "#EE64AC", "#59E1E3", "#403C3D"]
brights = ["#BDB3B1", "#F9CEC3", "#FADAD1", "#F9CBBE", "#948C8A", "#302C2D", "#F9CBBE", "#201C1D"]

